ALTER TABLE games
ADD COLUMN q1_home INTEGER,
ADD COLUMN q1_away INTEGER,
ADD COLUMN q2_home INTEGER,
ADD COLUMN q2_away INTEGER,
ADD COLUMN q3_home INTEGER,
ADD COLUMN q3_away INTEGER,
ADD COLUMN q4_home INTEGER,
ADD COLUMN q4_away INTEGER;
